#!/usr/bin/env sh
# generates a man file from README using pandoc

pandoc --version 2>&1 > /dev/null || {
	printf '\e[1m%s\e[0m\n' \
		'Please install pandoc if you want a man file.' 1>&2
	exit 1
}

{
	# generate man page information
	ver="$(./kagami --version | egrep -o 'v([0-9].?)+' | head -n 1)"
	cat <<- EOF
		---
		title: kagami
		section: 1
		header: User Commands
		footer: $ver
		date: $(git log -1 --format='%ad')
		---
		# NAME
		$(./kagami --version | head -n 1 | sed "s/$ver//")

		# SYNOPSIS
		kagami [OPTIONS]

		# DESCRIPTION
	EOF

	# omit title first heading
	# capitalize document headings
	sed -E -e '1,/^#.*kagami/d' -e 's/^(# .*)/\U\1/g' < readme.md

	# append author information
	cat <<- EOF

		# AUTHOR
		$(./kagami --version | head -n 2 | tail -n 1)
	EOF
} | pandoc - -s -t man -o -

